version: "3.9"

services:
  db:
    image: postgres:13
    container_name: notes_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  notesapp:
    build: .
    container_name: notes-app
  
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "3500:3500"

volumes:
  db_data:

